import { strict as assert } from "node:assert";
import { writeFile } from "node:fs/promises";
import { setup,Session,db,compose,poll } from "./test-support";
import { source } from "./fixtures";
await setup(process.env.SKIP_BUILD!=="1");const a=new Session(),b=new Session(),key=crypto.randomUUID(),f=new FormData();
for(const [name,text] of [["one.md",source],["two.md",source+" second"],["blocked.md","NATO RESTRICTED"]])f.append("file",new Blob([text]),name);
f.append("target_language","german");
const prepared=await a.request("/api/translation-groups",f,key);assert.equal(prepared.code,202);const id=prepared.data.group_id;
const g=await poll(async()=>(await a.request(`/api/translation-groups/${id}`)).data,g=>g.children.every((c:any)=>["AWAITING_APPROVAL","FAILED"].includes(c.stage)));
assert.equal(g.children.filter((c:any)=>c.stage==="FAILED").length,1);
assert.equal((await b.request(`/api/translation-groups/${id}`)).code,404);
const maximum=g.children.reduce((n:number,c:any)=>n+(c.quote?.maximum_reserved_usd??0),0);
const good=g.children.filter((c:any)=>c.quote),blocked=g.children.find((c:any)=>!c.quote);
assert.equal((await a.start(good[0])).code,409);
assert.equal((await a.request(`/api/translation-groups/${id}/start`,JSON.stringify({quote_version:g.quote_version,max_total_cost_usd:.00001}),crypto.randomUUID())).code,409);
db("insert into test_gates(name,enabled,hits) values('group-child-started',true,0) on conflict(name) do update set enabled=true,hits=0");
const startKey=crypto.randomUUID(),body=JSON.stringify({quote_version:g.quote_version,max_total_cost_usd:maximum});
const pending=a.request(`/api/translation-groups/${id}/start`,body,startKey).catch(()=>null);
await poll(async()=>Number(db("select hits from test_gates where name='group-child-started'")),n=>n>0);
compose(["kill","-s","SIGKILL","api"]);await pending;db("update test_gates set enabled=false where name='group-child-started'");
const first=await poll(async()=>db(`select stage from jobs where id='${good[0].job_id}'`),s=>s==="SUCCEEDED");
const firstHash=db(`select artifact->>'hash' from jobs where id='${good[0].job_id}'`);
const firstCalls=db(`select count(*) from fake_events where job_id='${good[0].job_id}'`);
compose(["up","-d","--wait","api"]);
const raced=await Promise.all([a.request(`/api/translation-groups/${id}/start`,body,startKey),a.request(`/api/translation-groups/${id}/start`,body,startKey)]);
assert.ok(raced.every(r=>r.code===200));
for(const c of good)assert.equal((await a.done(c.job_id)).stage,"SUCCEEDED");
assert.equal(db(`select artifact->>'hash' from jobs where id='${good[0].job_id}'`),firstHash);
assert.equal(db(`select count(*) from fake_events where job_id='${good[0].job_id}'`),firstCalls);
assert.equal(db(`select count(*) from calls where job_id='${blocked.job_id}'`),"0");
assert.equal(db(`select count(*) from group_starts where group_id='${id}'`),"1");
assert.equal((await a.request(`/api/translation-groups/${id}/start`,JSON.stringify({quote_version:g.quote_version,max_total_cost_usd:2}),startKey)).code,409);
const cost=Number(db(`select coalesce(sum(cost),0) from calls c join jobs j on j.id=c.job_id where j.group_id='${id}'`));assert.ok(cost<=maximum);
await writeFile("evidence/folder-chaos.json",JSON.stringify({group_id:id,children:3,completed:2,preflight_rejected:1,group_start_records:1,api_SIGKILL_after_first_child_start:true,completed_child_preserved:true,blocked_provider_calls:0,known_cost_usd:cost,approved_cap_usd:maximum,ownership_denied:true},null,2));
console.log(JSON.stringify({passed:true,evidence:"evidence/folder-chaos.json"}));
